### PR TITLE
Removed hacks for fixed functions and info about elections

### PR DESCRIPTION
**Pull request by KrisAphalon**

### CODE REVIEW

**Comment by KrisAphalon** [comment]
Coverage decreased because removed functions that were previously checked are no longer needed, merging.

**Comment by akrzyz** [comment]
Wow chat naprawili?

**Comment by KrisAphalon** [comment]
Konsolę dokładniej, jej hacki wywaliłem

**Comment by akrzyz** [comment]
zaktualizuje NN_start.js jak do domu wróce

**Pull request merged**
